name: waterreminder
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.2

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  connectivity_wrapper: ^1.0.5
  flushbar: ^1.10.4
  load: ^1.0.0
  simple_animations: ^1.3.3
  jiffy: ^4.0.0
  flutter_datetime_picker: ^1.5.0
  percent_indicator: ^2.1.3
  flutter_svg: ^0.21.0+1
  sqflite: ^2.0.0+3
  path: any
  pull_to_refresh: ^2.0.0
  flutter_icons: ^1.1.0
  permission_handler: ^7.1.0
  settings_ui: ^1.0.0
  fbutton: ^2.0.1
  wave_progress_widget: ^0.0.1
  intl: ^0.17.0
  bottom_navy_bar: ^5.6.0
  url_launcher: ^6.0.3
  flutter_slidable: ^0.6.0
  rflutter_alert: ^1.0.2
  google_mobile_ads: ^0.12.2
  flutter_local_notifications: ^5.0.0+4
  rxdart: ^0.27.0


  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/img/ 
  